# Generated by Django 3.0.5 on 2020-05-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=250)),
                ('album_logo', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('song_title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('cover_photo', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
