# Generated by Django 3.0.5 on 2020-05-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-id']},
        ),
    ]
