# Generated by Django 3.0.5 on 2020-05-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200525_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='music.SongComment'),
        ),
    ]
